version: "3.8"

services:
  web:
    build: .
    container_name: quiz-app-container
    image: brijesh35/my-quiz-app:latest
    command: python manage.py runserver 0.0.0.0:8000 &> /dev/null &
    ports:
      - 8000:8000